#define FMI_GUID "{abb4bff1-d423-4e02-90d9-011f519869ff}"

#define FMI_FARLEFTVAL 3
#define FMI_MIDLEFTVAL 5
#define FMI_MIDRIGHTVAL 6
#define FMI_FARRIGHTVAL 4
#define FMI_SERVOLEFTOUT 9
#define FMI_SERVORIGHTOUT 10
#define FMI_FORWARDSPEED 1
#define FMI_HIGHROTATE 2
#define FMI_MEDIUMROTATE 8
#define FMI_LOWROTATE 7
